-- ============================================================================
-- MIGRATION: Add match_source column to product_matches
-- ============================================================================
-- Purpose: Distinguish algorithm-generated matches from human-confirmed matches
--          so that match_products.py can DELETE only its own rows, leaving
--          human decisions intact across re-scrape cycles.
--
-- Background:
--   Before this migration, match_products.py used TRUNCATE to reset the table
--   on every run, destroying any human decisions.  After this migration it uses:
--     DELETE FROM product_matches WHERE match_source = 'algorithm'
--   Human-confirmed rows (match_source = 'human_confirmed') are left untouched.
--
-- Apply to an existing DB (already running, data must be preserved):
--   psql -h localhost -p 5433 -U postgres -d price_scraper \
--        -f database/add_match_source.sql
--
-- Safe to re-run (ADD COLUMN IF NOT EXISTS + idempotent backfill + IF NOT EXISTS index).
-- ============================================================================

ALTER TABLE product_matches
    ADD COLUMN IF NOT EXISTS match_source VARCHAR(20) NOT NULL DEFAULT 'algorithm'
        CHECK (match_source IN ('algorithm', 'human_confirmed'));

-- Backfill: all rows that existed before this migration are algorithm-generated.
-- The DEFAULT above covers new rows; this UPDATE covers existing ones.
UPDATE product_matches
   SET match_source = 'algorithm'
 WHERE match_source IS NULL;

-- Partial index for the tiny set of human-confirmed rows.
-- Used by apply_confirmed.py to verify a row still exists.
CREATE INDEX IF NOT EXISTS idx_pm_match_source_human
    ON product_matches(match_source)
    WHERE match_source = 'human_confirmed';

COMMENT ON COLUMN product_matches.match_source IS
    'algorithm = auto-generated by match_products.py | human_confirmed = confirmed via admin review UI';
